sudo: true
os: trusty
cache: false
env:
  matrix:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
  global:
  - secure: EDCib6AWW++bcH79gapgp0yVHaTnitpNvaZ+sVrDz0Zd2FlU8JSYW7SYUO26EdKOt+tTfTc5KuvXlSBuLA40N8UGBpp6u/mOtfXA0STm1rLnUQlChZ0HZu+iqg6lkXicn0vjs46jOuIXkQySujs0gEmQ4yu5vbbaHttJ+K6SrHOw5GGlpLBgqT4uYuF5eHvqkAV1giqs/QiGwvV918RDAv8vKRJJKqBg+nvH0WAMCDaHQe9f3s/gwyhZhpuFbEd0eBykTNL2M0gB96xVX/gWdWbMkOgDE5tdL6AAsrgskqI7IJ1Qbyy+UvzuVEoZknJ4fkKIDN0gyTCsxZ9Gy1QWgiQE7QzCxnS5t2LPpmunLUQzYBafKPE3ICSriRUoU3lMnrR6Ggxejdgx4zC8pFa2yjFOt2/td9f2OQn14xmSY6P07kKzWLZgGQyPbpT63ChF89Vkur0R9fjfGXjr/joXQ1XlHxzOCe0tj1CrU+QQojL0pBLMoPv5sBqA6dyUAdIpXMjhqW1CPIdsdAxqdsAMRy3pizduyXNlJKo1Am7+z86jd5SsTeH+/cwApxq7P46kLbvp0Zi8aR6I1U/8rvT+/dTpp4syweYwd7LV5UJXDS3ZNiauhrlxKqQ0em5s4ojgvaBYNKsycMWjYmJ+ZH5LvANC4nXCnYVKIBLV5fOgu/w=
  - secure: PM23DonKuNu9xhOKKJz3DsC5KObVLcEydl1NMtEV9b3QIOc/Gno4IEKVKRJBbeC74iH1frdk6/8ee7EGUQMQPHPWKUrjVg0HWNiomlwdLTwQ06/w+G49r4Omd/HjXbE3xDYZAEyfAKn+hZqUxV4zTiYB32+F8Y4xRkG7ijSEleL0YqCQ9esHJtBnlWKqd9DhktFCPJUk8bYyaMOL2OCS43MqIXCWQIqsaapdmu6gLA6k/KW06JiAJDFXCUS02xD23va1/2YBtH8QxZCb+AOGCh6mfm+Umjhj3Fdcu87TM2O0AE5wyJNcDi51yjzpAuAXVfW6A+ga3jSb1vO8ClRFlFLJKfaYCvEazsIFQoGgblf7bQkKD5AxK2z9W82FXZGvK+KByoFDjMTNZUUljO8x2TDj6qcM9cFXn8zxV1VFE/9Q54/wO+fZg4F8tyeBnHh9VVJpeOu3mQxio9Xrw6goroRMBkQIDWlmLOpzHpv/JyveyJKhGdhUOu5jmyEVK+5RSsOHuAdCubS01P91g2JzOUZlVfaCp1wRZENGxKxWGv2Y0I6n3saNXUK9JjEPJMFRe0GeIPj3T1RlIvryxNgex94UnaytJlXMXEowKnMSQ5r6x71VXVCi3l7IIEwB55IgqDFLczoi1SDq7YXA3v1ifqH7ETSIAfzBkTieGoIr8FQ=
  - secure: tbQBaRxxlvp6rYDT5IWhuW8UVPkMriofxwEcht6mzy/bTES1+JannbZmmltZzqpKaAClNtwwe4NzPBIpD1vaf68pAGq8NH50sj3Du+vAbmuULY4lWI8rA3/b50pJeOrMcRXcXgE+W+lXOFHXDgNUXFISMhUt4lFeGSCV5U68tsRbZ3l9PKaMpibakV9ANlsH0ZrnV+8Wwj+8m7lFETP2xOBkmhS/jF9VO/xmQrC71OZZv1HKBpQt8L+DboyLkvMW+26hEY997vx7rZsgA+gyqjhaXXYjr1GrFFA8J4LdaSkKszAUCk/mmdqxaNpSQqPZUBo4GlGNy99D05TLzqCNIaenCRP7ZX9r/2XlR2WZQe5Dv3AcFLyJoSvZGX4SLqYUED3VcQApU3HTJ+MEzmx7UbJLjZ/5s9y5MreN679PbI96YPzyyYV4/Jyk9iWrQXuGKr68BLedrc/cWr80F1+HrJOsYMYOqvan+sO6C9nu+q6fp3Ff2og3BKOHBffQwpdW+b7oL2beBNyGH8r5MD4MFEkSRHBB4l/VO3R6Iw/OkfQvTOnnSY5dy4G4wYJpxTMp2rJBc5uUr0l30YijNaJPDehTwcBoYSuiiqS547IxSM3UkBiSlNz3FFRdCgER3LMsZytN/3yYW/mNyu1W821elPAm5SZQBp4uBB1EGWOBtEY=
before_install:
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid 3MVG9n_HvETGhr3Ca6xYW2EQnKG3kIvPRzrGo7A9_31u1ycLHXCHovT08L4TiEve2S3o18Tp --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a DevHub
script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg --wait
  2
- sfdx force:org:display -u ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg --wait 10
- sfdx force:org:delete -u ciorg -p
